// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfResumeBrowsingSystem.Domain.Models;

namespace WpfResumeBrowsingSystem.Domain.Migrations
{
    [DbContext(typeof(ResumeBrowingSystemV00Context))]
    [Migration("20190420123634_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("WpfResumeBrowsingSystem.Domain.Models.Experiences", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("End")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("StaffSid")
                        .HasColumnName("Staff_Sid")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("date");

                    b.HasKey("Eid");

                    b.HasIndex("StaffSid")
                        .HasName("IX_Staff_Sid");

                    b.ToTable("Experiences","ResumeBrowingSystemV00");
                });

            modelBuilder.Entity("WpfResumeBrowsingSystem.Domain.Models.Staffs", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("Age")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<short?>("Image")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Post")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("School")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Sex")
                        .HasColumnType("char(1)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Tel")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Sid");

                    b.ToTable("Staffs","ResumeBrowingSystemV00");
                });

            modelBuilder.Entity("WpfResumeBrowsingSystem.Domain.Models.Experiences", b =>
                {
                    b.HasOne("WpfResumeBrowsingSystem.Domain.Models.Staffs", "StaffS")
                        .WithMany("Experiences")
                        .HasForeignKey("StaffSid");
                });
#pragma warning restore 612, 618
        }
    }
}
